package routes

import (
	"library-books/controllers/books"
	"library-books/controllers/users"
	"library-books/database/mongodb"
	_ "library-books/docs" // docs is generated by Swag CLI, you have to import it.
	"library-books/helpers"
	"library-books/middleware"
	"net/http"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/go-playground/validator/v10"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

func SetupRouter(validate *validator.Validate) *gin.Engine {
	router := gin.New()

	// connection mongodb database
	mongodb.Connect()

	// skip base url path
	router.Use(gin.LoggerWithConfig(gin.LoggerConfig{
		SkipPaths: []string{"/"},
	}))

	// register error handler RFC7807 spec
	router.Use(helpers.GinErrorHandler())

	// register localizer i18n
	localizerMiddleware := middleware.NewLocalizerMiddleware()
	router.Use(localizerMiddleware.Middleware())

	// gin recovery handle middleware error and enable cors configuration
	router.Use(gin.Recovery())
	router.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET", "PUT", "PATCH", "DELETE", "POST", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Authorization", "Content-Type"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// endpoint API for health checking
	router.GET("/ping", func(ctx *gin.Context) {
		ctx.JSON(http.StatusCreated, "Everything is working fine..")
	})

	// endpoint swagger
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// endpoint for group api
	group := router.Group("api/v1")
	{
		UsersGroup := group.Group("users", middleware.AuthMiddleware())
		UsersRoutes(UsersGroup, &users.UsersController{Validate: validate})

		AuthUsersGroup := group.Group("auth")
		AuthUsersRoutes(AuthUsersGroup, &users.UsersController{Validate: validate})

		BooksGroup := group.Group("books")
		BooksRoutes(BooksGroup, &books.BooksController{Validate: validate})
	}

	return router
}
